# Generated by Django 3.1.7 on 2021-05-21 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='created_Date',
            new_name='created_date',
        ),
    ]
